[project]
name = "SentinelOneSingularityOperationsCenter"
version = "2.0"
description = "SentinelOne Singularity Operations Center integration for Google SecOps SOAR."
requires-python = ">=3.11,<3.12"
dependencies = [
    "environmentcommon",
    "requests>=2.32.4",
    "tipcommon",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "soar-sdk",
    "integration-testing",
    "pytest-json-report>=1.5.0",
]

[tool.pytest.ini_options]
pythonpath = "."

[tool.ruff.lint]
ignore = [
    "G004",  # SOAR SiemplifyLogger does not support %s lazy evaluation (*args), so f-strings are required for logging.
]


[tool.uv.sources]
soar-sdk = { git = "https://github.com/chronicle/soar-sdk" }
tipcommon = { path = "../../../../packages/tipcommon/whls/TIPCommon-2.4.1-py3-none-any.whl" }
environmentcommon = { path = "../../../../packages/envcommon/whls/EnvironmentCommon-1.0.2-py2.py3-none-any.whl" }
integration-testing = { path = "../../../../packages/integration_testing_whls/integration_testing-2.2.10-py3-none-any.whl" }

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
