[project]
name = "CyberArkPAM"
version = "13.0"
description = "CyberArk's Privileged Access Manager is a full life-cycle solution for managing the most privileged accounts and SSH Keys in the enterprise. It enables organizations to secure, provision, manage, control and monitor all activities associated with all types of privileged identities."
requires-python = ">=3.11,<3.12"
dependencies = [
    "pyopenssl==25.3.0",
    "cryptography==46.0.7",
    "requests==2.32.5",
    "requests-toolbelt==1.0.0",
    "tipcommon",
    "pyyaml",
]

[dependency-groups]
dev = [
    "environmentcommon",
    "integration-testing",
    "pytest>=9.0.3",
    "pytest-json-report>=1.5.0",
    "soar-sdk",
]

[tool.uv]
[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.uv.sources]
soar-sdk = { git = "https://github.com/chronicle/soar-sdk.git" }
tipcommon = { path = "../../../../packages/tipcommon/whls/TIPCommon-2.4.1-py3-none-any.whl" }
integration-testing = { path = "../../../../packages/integration_testing_whls/integration_testing-2.4.1-py3-none-any.whl" }
environmentcommon = { path = "../../../../packages/envcommon/whls/EnvironmentCommon-1.0.3-py3-none-any.whl" }
